# This workflow will do a clean installation of node dependencies using Yarn, cache/restore them,
# build the source code and run tests across different versions of node.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI  # Name of the workflow

on:  # This specifies when the workflow will run
  push:  # Triggers the workflow on push events
    branches: [ "main" ] 

jobs:  # Defines the jobs to be run
  build:
    runs-on: self-hosted 

    strategy:  # A strategy matrix can run tests across different versions of Node.js
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4

    - name: Print environment PATH and Yarn version
      run: |
        echo $PATH
        yarn --version
        which yarn

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'  

    - name: Install dependencies
      run: yarn install --frozen-lockfile 

    - name: Build
      run: yarn build --if-present 
